fix

diff --git a/.github/workflows/ci-version-updater.yaml b/.github/workflows/ci-version-updater.yaml
--- a/.github/workflows/ci-version-updater.yaml
+++ b/.github/workflows/ci-version-updater.yaml
@@ -60,3 +60,34 @@ jobs:
           echo "servie_name=$servie_name"
           pwd
           python shared-workflows/.github/scripts/ci_version_updater.py --charts-root-path helm-charts --scope "${{ inputs.scope }}" --service-name "${servie_name}" --service-version ${{ github.ref_name }}
+
+      - name: Commit changes
+        run: |
+          cd helm-charts
+          git config --global user.name "mapcolonies[bot]"
+          git config --global user.email "devops[bot]@mapcolonies.com"
+
+          git add .
+          # Add "|| true" for not failing on this line
+          servie_name="${{ inputs.repository || github.event.repository.name }}"
+          git commit -m "chore: update charts for ${{ inputs.scope }}/${servie_name} with version ${{ github.ref_name }}" || true
+
+          success=false
+          for ((i=1; i<=5; i++)); do
+            echo "Attempt number $i"
+            if git push; then
+              success=true
+              break
+            else
+              sleep 5
+              # --ff for fast-forward
+              git pull origin feat/MAPCO-4702-image-updater --ff
+            fi
+          done
+
+          if [ "$success" = false ]; then
+            echo "Failed to push changes."
+            exit 1
+          fi
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
